Added login/logout
aodarc/final_project pull request #22
Opened 2018-02-13 16:51 UTC by Motrunich

Fix registration
added login/logout

2018-02-13 18:46 UTC, aodarc requested changes
check comments

2018-02-13 18:46 UTC, aodarc commented on templates/components/header.html
> -        <a class="nav-link" href="#">Личаківський</a>
```
{% for district in districts %}
<li class="nav-item">
        <a class="nav-link" href="?name={{district.name}}">{{district.name}}</a>
 </li>
{%endfor%}
```

2018-02-13 18:46 UTC, aodarc commented on apps/kindergarten/views.py
> +# class KindergartenView(ListView):
uncomment

2018-02-13 18:46 UTC, aodarc commented on apps/user_profile/views.py
> +def home(request):
remove it

2018-02-13 18:46 UTC, aodarc commented on apps/user_profile/views.py
> +class DistrictView(ListView):
do we need this?

2018-02-13 18:46 UTC, aodarc commented on apps/user_profile/views.py
> +def search_kinder(request):
move this logic to MainPageView

2018-02-13 18:46 UTC, aodarc commented on final_project/settings.py
> +                # 'django.core.context_processors.media',
clear it

2018-02-13 18:46 UTC, aodarc commented on final_project/settings.py
> +EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
it is default value

2018-02-13 18:46 UTC, aodarc commented on final_project/settings.py
> +LOGIN_REDIRECT_URL = 'main'
LOGIN_REDIRECT_URL = reverse_lazy('main')

2018-02-13 18:46 UTC, aodarc commented on templates/components/header.html
> +          <a class="nav-link" href="{% url 'search' %}">Личаківський</a>
use ?name=

2018-02-13 18:46 UTC, aodarc commented on templates/main_page/distrOne.html
> +{% extends 'base.html' %}
move this search form to main page

2018-02-13 19:00 UTC, Motrunich commented on apps/user_profile/views.py
> +def home(request):
Done

2018-02-13 19:01 UTC, Motrunich commented on final_project/settings.py
> +                # 'django.core.context_processors.media',
Done

2018-02-13 19:02 UTC, Motrunich commented on final_project/settings.py
> +EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
Done. Deleted

2018-02-14 19:45 UTC, Motrunich commented on apps/kindergarten/views.py
> +# class KindergartenView(ListView):
Done

2018-02-21 00:42 UTC, Motrunich commented on apps/user_profile/views.py
> +def search_kinder(request):
Done

2018-02-21 00:42 UTC, Motrunich commented on templates/components/header.html
> -        <a class="nav-link" href="#">Личаківський</a>
Done

2018-02-21 00:42 UTC, Motrunich commented on apps/user_profile/views.py
> +class DistrictView(ListView):
deleted

2018-02-21 00:43 UTC, Motrunich commented on templates/components/header.html
> +          <a class="nav-link" href="{% url 'search' %}">Личаківський</a>
done

2018-02-21 00:44 UTC, Motrunich commented on templates/main_page/distrOne.html
> +{% extends 'base.html' %}
done

2018-02-25 19:50 UTC, Motrunich commented on final_project/settings.py
> +LOGIN_REDIRECT_URL = 'main'
done

2018-02-26 16:05 UTC, maziar0andriy approved these changes

2018-03-01 17:08 UTC, closed without merging