S 19 child user profile map
aodarc/final_project pull request #5
Opened 2018-01-16 19:16 UTC by maziar0andriy

create child model

2018-01-16 21:22 UTC, aodarc requested changes
follow my comments

2018-01-16 21:22 UTC, aodarc commented on apps/user_profile/models.py
> +
pls remove blank lines between model fields

2018-01-16 21:22 UTC, aodarc commented on final_project/settings.py
> +        ,
why is it there)?

2018-01-16 21:22 UTC, aodarc commented on final_project/settings.py
> +STATIC_ROOT = 'static'
revert this

2018-01-16 21:22 UTC, aodarc commented on templates/base.html
> -  {% block header %}
why was it deleted?

2018-01-16 21:22 UTC, aodarc commented on templates/base.html
> -<script src="{% static 'final_project/bootstrap/js/bootstrap.min.js' %}"></script>
revert html files

2018-01-17 15:56 UTC, maziar0andriy commented on final_project/settings.py
> +        ,
because it was here))) delete it?

2018-01-17 15:58 UTC, maziar0andriy commented on final_project/settings.py
> +STATIC_ROOT = 'static'
ok

2018-01-17 15:59 UTC, maziar0andriy commented on templates/base.html
> -  {% block header %}
it so happened))

2018-01-17 15:59 UTC, maziar0andriy commented on templates/base.html
> -<script src="{% static 'final_project/bootstrap/js/bootstrap.min.js' %}"></script>
ok

2018-01-17 16:00 UTC, maziar0andriy commented on apps/user_profile/models.py
> +
ok

2018-01-25 12:42 UTC, merged