S 16 main page frontend
aodarc/final_project pull request #9
Opened 2018-01-29 21:30 UTC by Motrunich

S-16 Main page Frontend

2018-01-29 21:57 UTC, aodarc requested changes
w8ing for fixes

2018-01-29 21:57 UTC, aodarc commented on apps/user_profile/urls.py
> +    url(r'^register/$', RegisterFormView.as_view()),
you should add **name** attr to all urls

2018-01-29 21:57 UTC, aodarc commented on apps/user_profile/views.py
> +    success_url = "/login/"
use **reverce_lazy(url_name)**  function there

2018-01-30 08:48 UTC, aodarc approved these changes

2018-01-30 13:18 UTC, maziar0andriy approved these changes

2018-01-30 16:34 UTC, merged